export type Project = {
    title: string
    description: string
    tech: string[]
    tags: string[]
    status: "Live" | "Private" | "Archived" | "Completed" | "Prototype"
    link?: string
    image: string
}

export const portfolio = {
    contact: {
        name: "Ibrahim Nurul Huda",
        email: "Ibrahim@sarbeh.com",
        phone: "+6287884769999",
        linkedin: "https://linkedin.com/in/sarbeh",
        website: "https://sarbeh.com",
        location: "Jabodetabek, Indonesia",
    },

    narrative: {
        philosophy: [
            "Founder‑minded PM Intern yang membangun, mengukur, dan beriterasi cepat. Saya fokus pada discovery yang disiplin, delivery yang cepat namun terukur, dan alignment lintas fungsi yang rapi. Berpengalaman membangun produk end‑to‑end sebagai engineer × product builder, termasuk integrasi API, optimalisasi performa, dan data instrumentation untuk eksperimen.",
            'Saya thrive di tim kecil dengan pola Agile + Shape Up, fokus "ship  to measure  to adjust" dan keputusan berbasis discovery, bukan feeling.',
            "Karena bagi saya, product management bukan sekadar peran, melainkan sebuah panggilan untuk memiliki masalah secara mendalam dan menyelesaikannya dengan tuntas. Filosofi ini bukan sekadar teori bagi saya; ini adalah prinsip yang saya jalani secara langsung sebagai seorang founder dan product builder.",
            "Saya mendirikan PT saya sendiri, PT Cahaya Petunjuk Inovasi, dan sedang melalui seluruh siklus perjuangan: dari ide mentah, validasi pasar, hingga meluncurkan produk SaaS berbasis AI ke tangan pengguna. Pengalaman ini memberikan saya empati yang tidak ternilai. Saya tahu persis bagaimana rasanya tekanan untuk bergerak cepat, tantangan mengubah visi menjadi kenyataan dengan sumber daya terbatas, dan keharusan mutlak untuk fokus pada pemecahan masalah nyata pengguna.",
            "Dari perjalanan inilah, saya membangun sebuah kerangka kerja yang saya yakini sangat relevan untuk membantu para founder di Founderplus: Kepemilikan Penuh & Pola Pikir Product‑Based. Ini adalah mentalitas yang selalu saya terapkan, termasuk saat bekerja dengan klien seperti Founderplus saat sebagai fullstack engineer. Saya terbiasa menangani pekerjaan secara product‑based, bukan project‑based yang sekali selesai lalu ditinggal. Artinya, saya berharap bisa memiliki peran sebagai mitra jangka panjang yang fokus pada evolusi dan kesuksesan produk secara berkelanjutan. Oleh karena itu, saya tidak akan pernah menjadi 'ticket taker'. Saya terobsesi memahami 'mengapa' di balik setiap fitur, proaktif menantang asumsi, dan memastikan setiap detail mendukung tujuan produk.",
            "Eksekusi Pragmatis dengan Prinsip 'Ship, Measure, Adjust'. Saya paham betul bahwa di dunia startup, 'sempurna adalah musuh dari kemajuan.' Saya menerapkan metodologi agile yang pragmatis: meluncurkan solusi dengan cepat untuk mendapatkan feedback, mengukur dampaknya secara data‑driven, lalu melakukan penyesuaian. Pola pikir ini saya terapkan juga pada diri sendiri; saya terus‑menerus belajar lintas bidang agar bisa memberikan perspektif dan solusi yang lebih kaya dan tepat sasaran.",
            "Jembatan Strategis Antara Visi, Teknologi, dan Bisnis. Sebagai seorang 'Engineer × Product Builder', saya membawa perspektif yang unik. Saya tidak hanya bisa melihat gambaran besar dan bagaimana teknologi bisa menjadi akselerator untuk tujuan bisnis, tapi saya juga mengerti secara mendalam bagaimana cara membangunnya. Saya mampu menerjemahkan visi besar menjadi langkah‑langkah teknis yang realistis, membantu para founder membuat keputusan strategis yang cerdas, modern, dan menghindari jebakan teknis yang bisa menghabiskan waktu dan biaya.",
            "Singkatnya, saya tidak menawarkan diri sebagai mahasiswa magang pada umumnya yang ingin belajar teori. Saya datang sebagai seorang praktisi yang telah berada di 'medan perang' sebagai engineer yang sering berhadapan dengan product. Saya membawa paket lengkap: mindset kepemilikan seorang founder, metodologi eksekusi yang teruji, dan kemampuan untuk menjadi jembatan antara ide dan kenyataan. Semangat inilah yang ingin saya bawa untuk berkontribusi secara nyata bagi kesuksesan startup binaan Founderplus sejak hari pertama.",
        ],
        coCreation: {
            intro:
                "Co‑creation yang terstruktur. Saya memfasilitasi ideasi & keputusan bersama user, namun tetap disiplin sebelum eksekusi:",
            disciplines: [
                "Ada problem statement",
                "Assumption log",
                "Evidence (interview/logs)",
                "Success & counter‑metrics",
            ],
        },
        teamStyle: [
            "Shaping dulu (appetite, batasan scope, solution sketch).",
            "Sprint ringan berorientasi outcome (PRD 1‑pager, Now‑Next‑Later, rencana peluncuran/rollback).",
            "Measure  to Adjust (event schema siap sejak awal, review mingguan, iterasi cepat).",
        ],
        learningFocus: [
            "Business Model Canvas",
            "Customer Discovery/JTBD",
            "Strategic facilitation (opsi ↔ trade‑off ↔ keputusan).",
        ],
        guardrails: [
            "Hipotesis terukur + counter‑metric.",
            "Guide interview & insight deck.",
            "Experiment plan + read‑out.",
        ],
    },

    tools: [
        "Business Model Canvas",
        "User Story Mapping", 
        "Unit Economics Canvas",
        "Trello",
        "Notion",
        "Figma",
        "Excalidraw",
        "Microsoft Clarity",
        "GA4",
        "Umami",
        "DuckDB",
        "BigQuery",
        "Google Ads",
        "Facebook Ads",
        "TikTok Ads",
        "LinkedIn Ads",
        "Feature flag",
        "A/B testing",
        "GitHub",
        "GitLab",
        "Postman",
        "Swagger",
        "Playwright",
        "Stagehand",
        "OpenAI",
        "Mistral",
        "Gemini",
        "n8n",
        "Make",
        "Zapier",
        "Pipedream",
        "Activepieces",
        "Windmill",
        "Telegram Bot API",
        "WhatsApp Cloud API",
        "Slack Bolt/Workflows",
        "Discord Bot",
        "Cloudflare Workers/Queues/Cron",
        "Vercel",
        "AWS Lambda + EventBridge + Step Functions",
        "GCP Cloud Run + Pub/Sub + Scheduler",
        "Next.js",
        "React",
        "Svelte",
        "Astro",
        "Hono",
        "TailwindCSS",
        "SQLite",
        "PostgreSQL",
        "MySQL",
    ],

    skills: [
        {
            key: "discovery",
            name: "Discovery",
            summary:
                "Merancang & menjalankan interview/JTBD, memetakan pain  to opportunity, dan mengubah insight menjadi keputusan roadmap.",
            outputs: ["Problem statement tajam", "JTBD map", "Opportunity tree", "Insight deck"],
        },
        {
            key: "prioritization",
            name: "Prioritization",
            summary: "RICE/ICE dengan counter‑metric dan trade‑off eksplisit untuk roadmap Now‑Next‑Later.",
            outputs: ["Matriks prioritas", "Alasan keputusan", "Risk log"],
        },
        {
            key: "delivery",
            name: "Delivery",
            summary: "Kunci scope MVP, PRD 1‑pager, alignment design–engineering, QA/UAT, peluncuran/rollback.",
            outputs: ["PRD 1‑pager + acceptance criteria", "Release plan", "Flag/guardrail"],
        },
        {
            key: "analytics",
            name: "Analytics",
            summary: "Event schema, query (SQL/duckdb), dashboard funnel, evaluasi eksperimen/A‑B.",
            outputs: ["Event taxonomy", "Funnel dashboard", "Experiment read‑out"],
        },
        {
            key: "growth",
            name: "Growth",
            summary: "Funnel Awareness  to Revenue, bottleneck, eksperimen activation/retention dengan hipotesis terukur.",
            outputs: ["Hypothesis brief", "Daftar eksperimen prioritas", "Cohort/retention view"],
        },
        {
            key: "tech",
            name: "Tech Fluency",
            summary: "Kontrak API/SDK, membaca kode/log, diskusi teknis setara engineer. Jembatan visi–teknologi–bisnis.",
            outputs: ["API contract", "Sequence diagram", "Postman collection"],
        },
        {
            key: "communication",
            name: "Communication",
            summary: "Memo konteks  to opsi  to keputusan, fasilitasi alignment, demo untuk buy‑in.",
            outputs: ["Decision memo", "Stakeholder map", "Meeting notes (action jelas)"],
        },
        {
            key: "saas-research",
            name: "SaaS Research & Competitive Analysis",
            summary:
                "Riset mendalam service SaaS eksternal, analisis pros/cons, rekomendasi optimasi (speed, scalability, ekonomis).",
            outputs: ["Comparative matrix", "Cost‑benefit analysis", "Technical recommendation brief", "Migration roadmap"],
        },
        {
            key: "leadership",
            name: "Leadership (intern level)  - Working  to Proficient",
            summary: "Fasilitasi keputusan, kelola konflik prioritas, jaga ritme eksekusi.",
            outputs: ["Ritual kerja (stand‑up/review/retro)", "Risiko & mitigasi disepakati"],
        },
        {
            key: "operational-excellence",
            name: "Operational Excellence & DevEx",
            summary: "Bottleneck hunting, CI/CD acceleration, testing maturity, documentation & ownership untuk meningkatkan developer productivity dan product reliability.",
            outputs: ["Performance audit & optimization plan", "CI/CD acceleration report", "Testing maturity roadmap", "Documentation & ownership map"],
        },
    ],

    proofDetails: [
        {
            title: "Sunat/Khitan Solo  - Funnel",
            points: [
                "Landing  to CTA +12pp",
                "CTA  to WA +15pp",
                "WA  to Booking +38pp (60%  to 98%)",
                "Total conversion 3.0%  to 8.5%",
            ],
        },
        {
            title: "FounderPlus  - Performa",
            points: ["Bundle size −75%", "TTI 2.3s  to 1.1s", "TTFB 800ms  to 320ms", "[Des 2024 | Lighthouse]"],
        },
        {
            title: "Bantu AI  - Aktivasi & Retensi",
            points: [
                "70+ pengguna aktif",
                "85% activation (first successful generation)",
                "60% D7 retention",
                "Multi‑provider setup: cost −40%, latency −60%, ROI hemat $200/bulan",
            ],
        },
        {
            title: "Operational Excellence & DevEx",
            points: [
                "Performance & Reliability: OOM rate 15%  to 0%, LCP 5.6s  to 1.8s, crash-free sessions 85%  to 98%",
                "CI/CD Acceleration: build time 10-15 menit  to 4-6 menit, deployment frequency 2x/week  to daily",
                "Testing Maturity: flaky test rate 25%  to 8%, regression count 12/month  to 3/month", 
                "Documentation & DevEx: onboarding time 2 minggu  to 5 hari, MTTR 4 jam  to 1.5 jam",
            ],
        },
    ],

    projects: [
        {
            title: "Private Company  - Optimisasi Website (WP + IG/YouTube API)",
            description:
                "Integrasi Instagram/YouTube API ke WordPress, SEO & Page Speed. Fokus visibilitas & UX lewat konten dinamis dan performa.",
            tech: ["WordPress", "Instagram API", "YouTube API", "SEO", "Page Speed", "PHP"],
            tags: ["Web", "SEO", "Performance", "Content"],
            status: "Private",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Bantu AI (B2C)  - Platform AI SaaS Islami",
            description:
                "Menghubungkan >50 model (Claude, GPT, Gemini), RAG rujukan Islam, web search, generatif, TTS/STT, transcription multilingual.",
            tech: ["VPS", "RAG", "Claude/GPT/Gemini", "Whisper STT", "Auth", "Billing"],
            tags: ["SaaS", "AI", "RAG"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Zikir & Doa  - App Mobile & Web",
            description:
                "Panduan zikir, doa, dan konseling AI berbasis RAG. Fitur: zikir pagi/sore, asma wa sifat, adab doa, kumpulan doa, konseling.",
            tech: ["Astro.js", "Hono.js", "Ionic", "OpenAI API", "RAG", "SQLite", "Auth"],
            tags: ["Web", "Mobile", "AI", "RAG"],
            status: "Private",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Kajian  - Daftar Kajian Islam",
            description: "Platform daftar kajian (judul, tempat, jadwal, peta, kategori).",
            tech: ["Apps Script", "HTMX", "AJAX", "AlpineJS", "AstroJS"],
            tags: ["Web", "Content"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Jadwal KRL Solo Jogja  - Pencarian Interaktif",
            description: "Favorit, tukar stasiun, rute. Antarmuka interaktif dan cepat.",
            tech: ["Interactive UI", "Client‑side filtering"],
            tags: ["Tooling", "Web"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "FounderPlus  - Landing Page i18n Super Cepat",
            description: "React; responsive & i18n; bundle size −75%  to TTI 2.3s  to 1.1s; TTFB 800ms  to 320ms.",
            tech: ["ReactJS", "TailwindCSS", "i18n", "DateFns", "TanStack Query"],
            tags: ["Web", "Performance"],
            status: "Live",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Nasihat Syaikh Ashim  - Konten Ringan",
            description: "Konten nasihat; web stack ringan.",
            tech: ["HonoJS", "AlpineJS", "Python", "TailwindCSS", "HTMX", "SQLite"],
            tags: ["Web", "Content"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Pokemon Go Clone  - Nearby & Catch",
            description: "Geolocation API + Leaflet + Svelte; Nearby Pokémon, Inventory, Settings.",
            tech: ["Svelte", "Leaflet", "Geolocation API"],
            tags: ["Playground", "Mobile", "Web"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "May Learnings Dashboard  - Analisis Twitter Campaign",
            description: "Dashboard performa kampanye Twitter.",
            tech: ["Hono", "Python", "AlpineJS", "ChartJS", "HTMX"],
            tags: ["Analytics", "Web", "Dashboard"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "AI Chat Taaruf  - Perantara Taaruf",
            description: "Text embed ke CV; Q&A umum; alur taaruf asistif.",
            tech: ["Cloudflare Worker", "Llama 3 8B", "HonoJS", "HTMX"],
            tags: ["AI", "Web"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Referensi Kutub  - Mazhab Syafi'i & Hanbali",
            description: "Referensi Kutub dengan performa ringan.",
            tech: ["Cloudflare Worker", "D1 SQLite", "HonoJS", "HTMX"],
            tags: ["Content", "Web"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Arbain  - Koleksi 40 Hadits",
            description: "Baca dan cari hadits dengan antarmuka sederhana.",
            tech: ["NuxtJS", "TailwindCSS", "Cloudflare Pages", "VueJS"],
            tags: ["Content", "Web"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Eklinik  - Manajemen Klinik Digital",
            description: "Registrasi, jadwal, rekam medis, laporan; dashboard admin.",
            tech: ["ReactJS", "PostgreSQL", "NextJS", "TailwindCSS"],
            tags: ["Web", "Dashboard"],
            status: "Private",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Murunah  - Platform Pembelajaran Al‑Quran",
            description: "Progress hafalan, jadwal murojaah, statistik, reminder harian.",
            tech: ["AlpineJS", "AstroJS", "TailwindCSS"],
            tags: ["Web", "Education"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Presensi  - Geolocation Check‑in/out",
            description: "Laporan kehadiran dan dashboard admin.",
            tech: ["AlpineJS", "SvelteJS", "AstroJS", "TailwindCSS"],
            tags: ["Web", "Tooling", "Dashboard"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Shortener  - URL Shortener + Analytics",
            description: "Custom alias, statistik klik, batch processing, preview real‑time.",
            tech: ["MySQL", "SvelteJS", "AstroJS", "TailwindCSS"],
            tags: ["Tooling", "Web", "Analytics"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Yayasan Naik Kelas  - Donasi & Program Pendidikan",
            description: "Galang dana online, tracking progress, dan laporan transparansi.",
            tech: ["SvelteJS", "AstroJS", "TailwindCSS", "Apps Script"],
            tags: ["Web", "Nonprofit"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Compress  - Image Compressor Client‑side",
            description: "Kompresi gambar tanpa upload; batch; preview real‑time.",
            tech: ["WebWorker", "SvelteJS", "AstroJS", "TailwindCSS"],
            tags: ["Tooling", "Web"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Jadwal KRL  - Pencarian Jadwal Kereta",
            description: "Filter rute, waktu, estimasi perjalanan; UX ramah.",
            tech: ["SvelteKit", "TailwindCSS"],
            tags: ["Tooling", "Web"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Qlm One  - Link‑in‑bio + Canvas Ucapan",
            description: "Link‑in‑bio dengan kanvas ucapan hari raya.",
            tech: ["Svelte", "UnoCSS", "Canvas", "AstroJS"],
            tags: ["Web", "Tooling"],
            status: "Archived",
            image: "/placeholder.svg?height=360&width=640",
        },
        {
            title: "Sistem Perpajakan AMIKOM (2023)  - UI Frontend",
            description: "Implementasi UI Frontend untuk sistem perpajakan.",
            tech: ["React", "TypeScript", "Vite", "Tailwind"],
            tags: ["Web", "Frontend"],
            status: "Completed",
            image: "/placeholder.svg?height=360&width=640",
        },
    ] as Project[],

    caseStudies: [
        {
            id: "founderplus",
            title: "6.1 FounderPlus  - i18n Landing, −75% Bundle  to TTI 1.1s",
            situation: "React landing butuh i18n & performa tinggi, tim kecil dan waktu terbatas.",
            task: "Turunkan bundle size & percepat TTI tanpa mengorbankan i18n.",
            constraints: "Deadline kampanye, resource FE terbatas.",
            strategy: [
                "Audit bundling & network waterfall; identifikasi modul berat.",
                "Code‑split, lazy media, tree‑shaking, dan analitik per route.",
                "RICE untuk urutan pengerjaan.",
            ],
            solution: [
                "Pemecahan bundle + preloading resource kritikal.",
                "Refactor komponen berat dan pengurangan dependensi.",
            ],
            delivery: ["Now‑Next‑Later, PRD 1‑pager, rencana rollback."],
            measurement: ["Bandingkan TTI/TTFB/LCP; monitor error.", "PageSpeed (mobile/desktop) untuk verifikasi."],
            results: ["Bundle −75%; TTI 2.3s  to 1.1s; TTFB 800ms  to 320ms; LCP ~40% lebih baik."],
            next: ["In‑app experiments untuk hero/video; image CDN."],
        },
        {
            id: "landing-overhaul",
            title: "6.2 Landing Experiments & Tracking Overhaul  - Zero  to Measured Funnel",
            situation:
                "Konversi 0 dan tracking sulit (GA4 tidak andal), input Zoho manual, belum ada A/B testing, SEO funnel & sitemap belum ada.",
            task: "Bangun funnel yang bisa diukur, eksperimen multi‑style, perbaiki SEO & PageSpeed, integrasikan checkout ke website academy.",
            constraints: "Tim kecil, waktu terbatas, ketergantungan konten/kreasi iklan.",
            strategy: [
                "6 varian landing (psikologi + copy berbeda).",
                "PageSpeed '100' (lab) via code‑split, lazy media, critical CSS, caching.",
                "SEO full: on‑page, schema, internal linking, sitemap XML  to Google Search Console.",
                "Tracking: event schema baru; Microsoft Clarity (heatmap/session); UTM standar; sinkron Zoho (otomasi input).",
                "Checkout integration: deep‑link ke academy untuk memotong langkah.",
            ],
            solution: [
                "6 LP aktif (feature flag), event tracking siap pakai, sitemap+indexing, Clarity, jalur checkout langsung.",
            ],
            delivery: ["Rollout bertahap (canary 1–2 LP  to semua), change‑log & rollback plan."],
            measurement: [
                "Page Speed: PageSpeed (mobile/desktop), LCP/CLS/TBT.",
                "Funnel: Landing toCTA CTR, CTA toInterest Click, Academy toCheckout, Total conversion.",
                "SEO: non‑brand clicks/impressions, CTR SERP, jumlah halaman terindeks.",
                "UX (Clarity): scroll depth, dead/rage clicks, time‑to‑first‑action.",
            ],
            results: [
                "15 conversions; 4.41% dari 340 sesi LP / 2.78% dari 540 total sesi.",
                "Landing toCTA 16.47% (56/340); CTA toConvert 26.79% (15/56).",
                "Engagement: Pages/session 2.64, Scroll depth 55.15%, Active time 1.1 menit.",
                "PageSpeed: Mobile 41  to 95; LCP 5.6s  to 1.8s; CLS 0.25  to 0.03; TBT 520ms  to 70ms.",
            ],
            extras: [
                "Ringkasan angka: 0  to 15 conversions; 4.41% (dari 340 sesi LP) / 2.78% (dari 540 total sesi).",
                "Tahap Funnel  - Before/After/Δ:",
                "• Visit  to Landing: −  to 340/540 (62.96%)  to +62.96pp",
                "• Landing  to CTA: 0%  to 56/340 (16.47%)  to +16.47pp",
                "• CTA  to Convert: 0%  to 15/56 (26.79%)  to +26.79pp",
                "• Total Convert: 0%  to 2.78%  to +2.78pp",
            ],
            next: [
                'Kalibrasi varian menang  to iterasi copy/visual, tambah halaman "situasi", cohort pasca‑akuisisi, otomasi CRM end‑to‑end.',
            ],
        },
        {
            id: "bantu-ai",
            title: "6.4 Bantu AI Project (B2C)  - AI SaaS Islami",
            situation: "Banyak pengguna ingin memanfaatkan AI tanpa mengorbankan prinsip & rujukan Islami.",
            task: "Bangun platform AI B2C yang menyatukan >50 model, RAG rujukan, web search, generatif, TTS/STT, dan multilingual transcription.",
            constraints: "Tim kecil; biaya infrastruktur efisien; akurasi & kredibilitas rujukan wajib dijaga.",
            strategy: [
                "VPS‑based infra + orkestrasi pipeline; guardrail konten.",
                "RAG untuk pencarian rujukan; observabilitas (logging & rate‑limit).",
            ],
            solution: [
                "Model hub: Claude/GPT/Gemini + custom models.",
                "RAG untuk pencarian rujukan; Web search & generation.",
                "STT (Whisper) & text‑to‑image (Flux Pro, Pollination).",
                "Auth & billing dasar; onboarding ringkas.",
            ],
            delivery: ["Iterasi mingguan; feature flag; dokumentasi API internal."],
            measurement: [
                "Activation (first successful generation)",
                "7‑day retention",
                "Task success with reference",
                "Cost per 1k tokens",
            ],
            results: [
                "Komunitas 70+ pengguna aktif; 85% activation rate; 60% 7‑day retention.",
                "Search rujukan 200+ query/hari; biaya operasional $45/bulan.",
            ],
            next: ["Hardening RAG (korpus & evaluator), pricing tier, referral program, dashboard usage."],
        },
        {
            id: "ecommerce-migration",
            title: "6.5 E‑commerce Migration  - Tokopedia  to Shopify",
            situation: "Banyak seller tergantung marketplace, sulit kontrol brand/margin/data.",
            task: "Migrasi ekosistem seller ke Shopify dengan downtime minimal sambil meningkatkan performansi & konversi.",
            constraints:
                "Variasi struktur data marketplace; integrasi pembayaran/logistik lokal; SEO & konten Bahasa Indonesia.",
            strategy: [
                "Automated migration pipelines (produk, pelanggan, ulasan) lintas marketplace.",
                "Liquid + React Router untuk routing dinamis & halaman terlokalisasi.",
                "Local SEO + konten BI; PWA mobile‑first.",
                "Integrasi GoPay/OVO/DANA & JNE/J&T/SiCepat.",
                "Auto‑generated landing pages; analytics end‑to‑end + A/B testing.",
            ],
            solution: [
                "Migrasi batch + verifikasi data; tema Shopify teroptimasi; payment & shipping lokal; baseline SEO & tracking.",
            ],
            delivery: ["Blue‑green cut‑over; monitoring checkout; rollback plan."],
            measurement: ["Checkout success rate, CVR, LCP/TTFB, SEO (impressions/CTR), RPU pasca‑migrasi."],
            results: [
                "Waktu migrasi 3–5 hari.",
                "CVR +35%.",
                "LCP 3.1s  to 1.4s.",
                "CTR +28%.",
                "Komplain operasional turun 60%, customer satisfaction 4.6/5.",
            ],
            next: ["Playbook migrasi multi‑tenant, campaign templates untuk akuisisi, cohort analysis pasca peluncuran."],
        },
        {
            id: "operational-excellence",
            title: "6.6 Operational Excellence & Product Stewardship",
            situation: "FounderPlus mengalami halaman tertentu gagal dibuka (OOM) + pipeline build/deploy lambat (10-15 menit) yang menghambat development velocity dan user experience.",
            task: "Pulihkan keandalan halaman & percepat time-to-ship melalui performance optimization, CI/CD acceleration, dan testing maturity improvements.",
            constraints: "Tim development fokus pada fitur baru, budget maintenance terbatas, requirement zero-downtime untuk production.",
            strategy: [
                "Performance & Reliability: profiling memori, bundle splitting, lazy/priority loading untuk mengatasi OOM.",
                "CI/CD Acceleration: implementasi caching node_modules, test splitting, artifact reuse, parallelization.",
                "Testing Maturity: API contract (OpenAPI), e2e automation, flaky-test budget enforcement.",
                "Documentation as Runway: README per modul, ADR (Architecture Decision Records), ownership mapping.",
            ],
            solution: [
                "Performance optimization: split bundle besar, implement lazy loading, memory profiling untuk identifikasi memory leaks.",
                "CI/CD pipeline: caching dependencies, parallel test execution, artifact reuse antar stages.",
                "Contract testing: OpenAPI schema validation, Playwright e2e automation, flaky test identification & fixing.",
                "Documentation system: structured README templates, decision logs, clear ownership boundaries.",
            ],
            delivery: [
                "Performance fixes: feature flag rollout per halaman yang dioptimasi.",
                "CI/CD improvements: gradual pipeline optimization dengan rollback plan.",
                "Testing infrastructure: contract-first development dengan automated validation.",
                "Documentation: knowledge transfer sessions dan onboarding checklist baru.",
            ],
            measurement: [
                "Time-to-Ship / Lead Time for Changes.",
                "Build/Deploy Time & Deployment Frequency.",
                "Crash-free sessions / OOM rate / Error rate.",
                "LCP/TTFB untuk halaman terdampak.",
                "Flaky test rate & regression count per release.",
                "Developer onboarding time & MTTR (Mean Time to Recovery).",
            ],
            results: [
                "Performance & Reliability: OOM rate 15%  to 0%, LCP 5.6s  to 1.8s, crash-free sessions 85%  to 98%.",
                "CI/CD Acceleration: build time 10-15 menit  to 4-6 menit, deployment frequency 2x/week  to daily.",
                "Testing Maturity: flaky test rate 25%  to 8%, regression count 12/month  to 3/month.",
                "Documentation & DevEx: onboarding time 2 minggu  to 5 hari, MTTR 4 jam  to 1.5 jam.",
            ],
            extras: [
                "Product Stewardship Approach: tidak hanya reactive bug fixing, tetapi proactive bottleneck hunting dan capacity planning.",
                "Developer Experience Focus: setiap optimasi diukur dari perspektif developer productivity dan confidence in shipping.",
                "Long-term Sustainability: architecture decisions documented dalam ADR untuk future team members.",
            ],
            next: [
                "Automated performance monitoring dengan alerting untuk early bottleneck detection.",
                "Performance budget enforcement dalam CI pipeline (bundle size, LCP thresholds).",
                "Standardized documentation templates dan automated onboarding checklist.",
                "Advanced testing strategies: visual regression, API contract evolution, chaos engineering.",
            ],
        },
    ],

    leadership: {
        intro:
            "Co‑creation: memimpin sesi discovery bareng user; rangkum ke problem/solution brief; prioritas berdasarkan impact vs effort & counter‑metric; eksperimen dengan read‑out.",
        points: [
            "Fasilitasi keputusan lintas fungsi, kelola konflik prioritas.",
            "Menjaga ritme eksekusi: stand‑up, review, retrospective.",
            "Dokumentasi singkat padat (PRD 1‑pager, decision memo).",
        ],
    },
}
